# Generated by Django 4.2.16 on 2024-11-19 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorapp', '0016_delete_pharmacymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.CharField(choices=[('In-stock', 'In-stock'), ('out-of-stock', 'out-of-stock')], max_length=25)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorapp.prescription')),
            ],
        ),
    ]
