# Generated by Django 4.2.16 on 2024-11-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0002_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
