# Generated by Django 4.2.16 on 2024-11-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_doctorprofile_user_patientprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=10, null=True),
        ),
    ]
