# Generated by Django 4.2.16 on 2024-11-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0003_remove_medicalhistory_diagnosis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TreatmentPlan',
        ),
    ]
