# Generated by Django 4.2.16 on 2024-11-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0004_delete_treatmentplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='doctor',
        ),
    ]
