# Generated by Django 4.2.16 on 2024-11-16 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_payment_appointment'),
        ('doctorapp', '0005_remove_medicalhistory_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='diagnosis',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.doctorprofile'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='treatment_description',
            field=models.TextField(null=True),
        ),
    ]
