# Generated by Django 4.2.16 on 2024-11-17 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0006_medicalhistory_diagnosis_medicalhistory_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorapp.medicalhistory'),
        ),
    ]
