# Generated by Django 4.2.16 on 2024-11-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0010_alter_healtharticle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('In-Stock', 'In-Stock'), ('Out-Of-Stock', 'Out-Of-Stock')], max_length=100)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorapp.prescription')),
            ],
        ),
    ]
