# Generated by Django 4.2.16 on 2024-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0012_pharmacy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Admin', 'Admin'), ('Pharmacy', 'Pharmacy')], max_length=10, null=True),
        ),
    ]
