# Generated by Django 4.2.16 on 2024-11-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0013_pharmacy_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
