# Generated by Django 4.2.16 on 2024-11-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorapp', '0015_pharmacymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PharmacyModel',
        ),
    ]
